import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";
import Navigation from '../components/nav/Navigation';
import Footer from '../components/Footer';


export const metadata: Metadata = {
  title: "Create App",
  description: "Generated by app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Link href='/'>HOME</Link> <br />
        <Link href="/about">About</Link> <br />
        <Link href="/login">Login</Link> */}
        <Navigation />
        
        {children}

        <Footer/>
      </body>
    </html>
  );
}
